# Generated by Django 3.2.18 on 2023-03-23 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_since',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
