# Generated by Django 3.2.18 on 2023-04-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='followed',
            field=models.ManyToManyField(related_name='_main_customer_followed_+', to='main.Doctor'),
        ),
    ]
